version '3.7'

services:

  mixer-testnet:
    container-name: mixer-testnet
    build:
      context: ../contracts
      dockerfile: ../contracts/Dockerfile
    ports:
      - "8575:8575"
    networks:
      - "mixer-net"

networks:
  mixer-net:
