version: '3.7'

services: 
  mixer-backend: 
    container_name: mixer-backend

    build:
      context: ../backend

    ports:
      - "3000:3000"
    networks:
      - "mixer-net"

  mixer-testnet:
    container_name: mixer-testnet
    build:
      context: ../contracts
      dockerfile: ../contracts/Dockerfile
    ports:
      - "8575:8575"
    networks:
      - "mixer-net"


networks:
  mixer-net:
