---
env: 'docker-dev'
mixAmtEth: "0.1"
operatorFeeEth: "0.0005"

chain:
  url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
  chainId: 42
  mix:
    gasLimit: 8000000
  privateKeysPath: "/run/secrets/privateKeysPath"
  deployedAddresses:
    MiMC: "0xA8Da3D8f5c959Ac76281E5BA417D2fBFB7911194"
    MultipleMerkleTree: "0x8c27e86178336129fcf21c5d61a666cf8d66c59f"
    Semaphore: "0x7ff3181a24a82e581099a6a8733dbb028debf7c7"
    Mixer: "0xfb2bf70382a98c72d38bed63735ff5115ff243c6"

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKeyPath: "/run/secrets/hotWalletPrivKeyPath"
  etcd:
    host: "mixer-etcd"
    port: 2379
    lockTime: 7000

frontend:
  snarks:
    paths:
      verificationKey: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/verification_key.json'
      provingKey: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/proving_key.bin'
      circuit: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/circuit.json'
  countdown:
    endsAtUtcMidnight: true
    endsAfterSecs: 5
  supportedNetworkName: "Kovan"
  supportedNetwork: 42
  blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
