---
env: 'docker-dev'
mixAmtEth: "0.1"
burnFeeEth: "0.0005"

chain:
  url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
  chainId: 42
  mix:
    gasLimit: 8000000
  privateKeysPath: "/run/secrets/privateKeysPath"
  deployedAddresses:
    MiMC: "0xb6E7e9EfD8C5c832D28429e69C5953b7C29fC5d3"
    MultipleMerkleTree: "0x16cCbA0e920cCc07f405603aC45463CDb563AcDF"
    Semaphore: "0x23AFCD399e0365Fee5aE0e25085f10616e2A517b"
    Mixer: "0x1B260ea27FdBa80E5bD430ff9eddd29509d28109"

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKeyPath: "/run/secrets/hotWalletPrivKeyPath"
  etcd:
    host: "mixer-etcd"
    port: 2379
    lockTime: 7000

frontend:
  snarks:
    paths:
      verificationKey: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/verification_key.json'
      provingKey: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/proving_key.bin'
      circuit: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/circuit.json'
  countdown:
    endsAtUtcMidnight: true
    endsAfterSecs: 5
  supportedNetworkName: "Kovan"
  supportedNetwork: 42
  blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
