---
env: 'docker'
mixAmtEth: 0.1
mixAmtTokens: 20
feeAmtEth: 0.001
feeAmtTokens: 2
tokenSym: 'DAI'
tokenDecimals: 18

chain:
  url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
  chainId: 42
  mix:
    gasLimit: 8000000
  privateKeysPath: "../kovanPrivateKeys.json"
  deployedAddresses:
    MiMC: '0x9DD726D927F9b406DcD0065a61124A31DC7A4D96'
    Semaphore: '0x5d7Df26340f4A16797597E07f99b27170CBe1bc8'
    Mixer: '0xCF321783a827d5422822a45f1F3543e3994f8361'
    TokenMixer: '0xcF95B8393321B03d7E50A7043eE580B9fF605E3b'
    TokenSemaphore: '0x0060FF11695ADBCBe0B751d3DEac45e415dA3D11'
    RelayerRegistry: '0xB6A62103bf0d44343cd1D0d1B9a3D106F7b06874'
    Token: '0xc4375b7de8af5a38a93548eb8453a498222c4ff2'

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKeyPath: "/run/secrets/hotWalletPrivKeyPath"
  broadcasterAddress: "0x53BE836678eA3Dbf7257ef32954184Ac06C2D4b1"
  etcd:
    host: "mixer-etcd"
    port: 2379
    lockTime: 7000

frontend:
  snarks:
    paths:
      verificationKey: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/audit_v1/verification_key.json'
      provingKey: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/audit_v1/proving_key.bin'
      circuit: 'https://kobigurk.s3.us-west-1.amazonaws.com/mixer/audit_v1/circuit.json'
  countdown:
    endsAtUtcMidnight: true
    endsAfterSecs: 5
  supportedNetworkName: "Kovan"
  supportedNetwork: 42
  blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
