---
env: 'local-dev'
mixAmtEth: "0.1"
operatorFeeEth: "0.0005"

chain:
  url: "http://localhost:8545"
  chainId: 1234
  mix:
    gasLimit: 8000000
  privateKeysPath: "../ganachePrivateKeys.json"
  deployedAddresses:
    MiMC: '0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0'
    MultipleMerkleTree: '0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da'
    Semaphore: '0x345cA3e014Aaf5dcA488057592ee47305D9B3e10'
    Mixer: '0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF'

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKey: "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
  etcd:
    host: "localhost"
    port: 2379
    lockTime: 7000
  testing:
    privKeys:
      - "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
      - "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"

frontend:
  snarks:
    paths:
      verificationKey: '/build/verification_key.json'
      circuit: '/build/circuit.json'
      provingKey: '/build/proving_key.bin'
  countdown:
    endsAtUtcMidnight: false
    endsAfterSecs: 5
  supportedNetworkName: "local"
  supportedNetwork: 1234
  blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
