---
env: 'local-dev'
mixAmtEth: "0.1"
operatorFeeEth: "0.0005"

chain:
  url: "http://localhost:8545"
  chainId: 1234
  mix:
    gasLimit: 8000000

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKey: "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
  etcd:
    host: "localhost"
    port: 2379
    lockTime: 7000
